apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
#kubernetesVersion: stable
kubernetesVersion: v1.15.0
#controlPlane:
#  localAPIEndpoint:
#    advertiseAddress: 172.16.66.101
#    bindPort: 6443
#controlPlaneEndpoint: "LOAD_BALANCER_DNS:LOAD_BALANCER_PORT"
controlPlaneEndpoint: "172.16.66.101:6443"
etcd:
  external:
    endpoints:
    - https://172.16.66.101:2379
    - https://172.16.66.200:2379
    - https://172.16.66.201:2379
    caFile: /etc/kubernetes/pki/etcd/ca.crt
    certFile: /etc/kubernetes/pki/apiserver-etcd-client.crt
    keyFile: /etc/kubernetes/pki/apiserver-etcd-client.key
networking:
  podSubnet: "10.244.0.0/16"
