apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nexus-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: 1024m
    #nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: nexus
          servicePort: 80
        path: /nexus
      #- backend:
      #    serviceName: nexus
      #    servicePort: 5000
      #  path: /docker
  - host: docker.ted.com
    http:
      paths:
      - path: /
        backend:
          serviceName: nexus
          servicePort: 5000
