---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maven-cache
  namespace: ci
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: ceph-rbd
