apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-pvc
spec:
  containers:
  - image: ubuntu:16.04
    name: ubuntu
    volumeMounts:
    - mountPath: "/data"  	
      name: myvol
    tty: true
  volumes:
  - name: myvol
    persistentVolumeClaim:
      claimName: test-pvc
  #nodeSelector:
  #  kubernetes.io/hostname: node0
