apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellopy
spec:
  selector:
    matchLabels:
      app: hellopy
  replicas: 2 
  template:
    metadata:
      labels:
        app: hellopy
    spec:
      containers:
      - name: hellopy
        image: docker.ted.mighty/hellopy:latest
        imagePullPolicy: Always
        env:
        - name: REDIS_HOST
          # "svc.cluster.local": Local k8s cluster service
          # "data.": data namespace
          # "redis": Redis service name
          value: "redis.data.svc.cluster.local"
        - name: REDIS_PASS
          value: "P@ssw0rd"
        ports:
        - containerPort: 8000 
      imagePullSecrets:
      - name: nexuscred
---
apiVersion: v1
kind: Service
metadata:
  name: hellopy
spec:
  #type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  selector:
    app: hellopy

