apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-nfs
spec:
  capacity:
    storage: 4Gi
  accessModes:
  #- ReadWriteOnce
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mynfs
  mountOptions:
    - soft
    - intr
    - nfsvers=4.1
  nfs:
    server: 172.16.66.101
    path: /pan
