apiVersion: v1
kind: ReplicationController
metadata:
  name: ted-rc
spec:
  replicas: 2
  selector:
    app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: hellopy
        image: ski2per/hellopy
        env:
        - name: REDIS_HOST
          value: "redis-master"
        - name: REDIS_PASS
          value: "P@ssw0rd"
        ports:
        - containerPort: 80
        

