---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc2
  namespace: test
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: csi-rbd-sc
