FROM maven:3.3.9-jdk-8
LABEL MAINTAINER="Ted <ski2per@gmail.com>"
#COPY settings-aliyun.xml /root/.m2/settings.xml
COPY settings.xml /root/.m2/settings.xml
COPY settings-security.xml /root/.m2/settings-security.xml
