apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: ci
  name: docker-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 1024m
spec:
  tls:
  - hosts:
    - ted.mighty
    secretName: default/ted-mighty-tls
  rules:
  - host: docker.ted.mighty
    http:
      paths:
      - path: /
        backend:
          serviceName: nexus
          servicePort: 5000
