---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rbd-pvc2
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
  storageClassName: csi-rbd-sc
