apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: raw-block-pvc2
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Block
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-rbd-sc
